### ISSUE TITLE
Error: Prelude.(!!): index too large

### ISSUE THREAD

**Issue by dflock** [AtomLinter/linter-shellcheck#25] opened 2015-08-18 23:33 UTC
I've just started using the linter-sheckcheck plugin with atom 1.0.7. I've started getting these messages stacking up on the right hand side of the editor window - a new one every time I trigger linting.

This is when linting a large-ish bash script (480 lines) - although it seemed to be fine for ~1hr and then started doing this:

![screenshot - 15-08-18 - 04 18 54 pm](https://cloud.githubusercontent.com/assets/47756/9345376/0704864a-45c5-11e5-9ba2-e45994e1d434.png)

```
Error: Prelude.(!!): index too large
    at exit (/home/duncan/.atom/packages/linter-shellcheck/node_modules/atom-linter/lib/helpers.coffee:74:29)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:166:7)
    at Pipe.close (net.js:464:12)
```

### System Details:

```
$ shellcheck --version

ShellCheck - shell script analysis tool
version: 0.3.3
license: GNU Affero General Public License, version 3
website: http://www.shellcheck.net

$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 13.10
Release:	13.10
Codename:	saucy
```

Linting the same script on the command line using `shellcheck` works fine. I've tried restarting atom, but the errors start happening again as soon as I start editing the bash script again.

**Comment by djk** [comment] 2015-08-21 10:37
This is happening to me as well but on Mac OS X.

**Comment by cjwelborn** [comment] 2015-08-31 13:45
Same for me.

Binary | Version
---|---
Atom: | 1.0.9
Shellcheck: |  0.3.3
Shellcheck plugin: | 1.0.1

**Comment by steelbrain** [comment] 2015-08-31 13:52
@cjwelborn Well. It's the `shellcheck` exe that's causing the error, I assume you'll get the same error when you invoke that from cli

**Comment by cjwelborn** [comment] 2015-08-31 14:50
@steelbrain I see now. I couldn't tell that it was coming from `shellcheck` because the `Error Prelude.(!!)` message was confusing. It's a Haskell thing, so I should've known. I still can't reproduce it on the command line. Whatever triggers it goes away as I'm typing, but if I manage to catch it I will forward it to @koalaman (https://github.com/koalaman/shellcheck).

**Comment by koalaman** [comment] 2015-08-31 17:46
There was a bug where `shellcheck -f gcc file` would crash with this message when `file` was empty. It was fixed about a year ago for shellcheck 0.3.5.

**Comment by dflock** [comment] 2015-08-31 21:17
I've updated to 0.3.7 and this seems to have gone away.

As shellcheck is either statically compiled or has minimal dependencies, you can probably just install the latest version from here: https://launchpad.net/ubuntu/+source/shellcheck - this is what I did and it worked fine.

**Comment by cjwelborn** [comment] 2015-08-31 21:21
@dflock, shortly after my last comment I ditched the debian package (`v. 0.3.3`) and installed from source. I'm running `shellcheck v. 0.3.8` now and I haven't seen the error either (since updating).

**Comment by steelbrain** [comment] 2015-08-31 22:39
Closing based on comments above

**Closed by steelbrain** 2015-08-31 22:39 UTC

**Comment by andrewelkins** [comment] 2015-10-13 21:38
Updated to 0.3.7 and it went away for me as well.
